import os
import time
import secrets
import urllib.parse
import httpx
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID", "")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "")
REDIRECT_URI = os.getenv("REDIRECT_URI", "http://127.0.0.1:8000/callback")
SCOPES = "playlist-read-private playlist-read-collaborative playlist-modify-public playlist-modify-private"

AUTH_URL = "https://accounts.spotify.com/authorize"
TOKEN_URL = "https://accounts.spotify.com/api/token"
API_BASE = "https://api.spotify.com/v1"


def build_auth_url(state: str) -> str:
    params = {
        "client_id": CLIENT_ID,
        "response_type": "code",
        "redirect_uri": REDIRECT_URI,
        "scope": SCOPES,
        "state": state,
        "show_dialog": "false",
    }
    return AUTH_URL + "?" + urllib.parse.urlencode(params)


def exchange_code(code: str) -> dict:
    resp = httpx.post(TOKEN_URL, data={
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": REDIRECT_URI,
    }, headers=_basic_auth_header())
    resp.raise_for_status()
    return resp.json()


def refresh_access_token(refresh_token: str) -> dict:
    resp = httpx.post(TOKEN_URL, data={
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }, headers=_basic_auth_header())
    resp.raise_for_status()
    return resp.json()


def _basic_auth_header() -> dict:
    import base64
    creds = base64.b64encode(f"{CLIENT_ID}:{CLIENT_SECRET}".encode()).decode()
    return {"Authorization": f"Basic {creds}"}


def _get(access_token: str, path: str, params: dict | None = None) -> dict:
    url = path if path.startswith("https://") else f"{API_BASE}{path}"
    resp = httpx.get(url, params=params,
                     headers={"Authorization": f"Bearer {access_token}"})
    resp.raise_for_status()
    return resp.json()


def get_current_user(access_token: str) -> dict:
    return _get(access_token, "/me")


def get_user_playlists(access_token: str) -> list[dict]:
    playlists = []
    url = "/me/playlists"
    params = {"limit": 50, "offset": 0}
    while url:
        data = _get(access_token, url, params)
        for item in data["items"]:
            if item:
                playlists.append({
                    "id": item["id"],
                    "name": item["name"],
                    "track_count": item["tracks"]["total"],
                    "image_url": item["images"][0]["url"] if item.get("images") else None,
                })
        if data.get("next") and len(playlists) < 200:
            url = data["next"]  # full URL, pass directly to _get
            params = None
        else:
            break
    return playlists


def get_playlist_tracks(access_token: str, playlist_id: str) -> list[dict]:
    tracks = []
    path = f"/playlists/{playlist_id}/tracks"
    params = {"limit": 100, "offset": 0, "fields": "next,items(track(id,name,artists,album(name,images),preview_url))"}
    while path:
        data = _get(access_token, path, params)
        for item in data.get("items", []):
            t = item.get("track")
            if not t or not t.get("id"):
                continue
            images = t.get("album", {}).get("images", [])
            tracks.append({
                "id": t["id"],
                "name": t["name"],
                "artist": ", ".join(a["name"] for a in t.get("artists", [])),
                "album": t.get("album", {}).get("name", ""),
                "image_url": images[0]["url"] if images else None,
                "preview_url": t.get("preview_url"),
                "playlist_id": playlist_id,
            })
        if data.get("next"):
            path = data["next"]  # full URL, pass directly to _get
            params = None
        else:
            break
    return tracks


def create_playlist(access_token: str, user_id: str, name: str, track_ids: list[str]) -> str:
    resp = httpx.post(
        f"{API_BASE}/users/{user_id}/playlists",
        json={"name": name, "public": False, "description": "Generated by Music Rank"},
        headers={"Authorization": f"Bearer {access_token}"},
    )
    resp.raise_for_status()
    playlist_id = resp.json()["id"]

    # Add tracks in chunks of 100
    for i in range(0, len(track_ids), 100):
        chunk = track_ids[i:i+100]
        uris = [f"spotify:track:{tid}" for tid in chunk]
        httpx.post(
            f"{API_BASE}/playlists/{playlist_id}/tracks",
            json={"uris": uris},
            headers={"Authorization": f"Bearer {access_token}"},
        ).raise_for_status()

    return playlist_id
